version: "3.7"
services:
  caddy:
    image: qmcgaw/caddy-scratch
    container_name: caddy
    volumes:
      - ./Caddyfile:/Caddyfile:ro
      - ./data:/data
      - ./srv:/srv:ro
    environment:
      - TZ=America/Montreal
    network_mode: bridge
    ports:
      - 80:8080/tcp
      - 443:8443/tcp
      - 2015:2015/tcp
    restart: always
